### ISSUE TITLE
notify text messy on startup

### ISSUE THREAD

**Issue by Greesea** [rexdf/CommandTrayHost#1]
|||
---|---
System | Windows 10 x64 1703 (15063.726)
System Language | Chinese
System Proxy|Unset

![screenshot](https://user-images.githubusercontent.com/9460513/33408701-dc6ebb82-d5b2-11e7-922b-ccdd679c6c06.png)

**Comment by hdstar2009** [comment]
同样简体中文win10 x64，每次启动同样这个信息提示。

**Comment by rexdf** [comment]
嗯 确认有这个问题。这个问题Appveyor的自动编译有。主要是它自动把我的`.cpp .h .rc`原文件全部从UTF-16转码成UTF-8了。我来修复下.
