### ISSUE TITLE
RC2135	file not found: Studio

### ISSUE THREAD

**Issue by bigtan** [rexdf/CommandTrayHost#2]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	RC2135	file not found: Studio	CommandTrayHost	C:\Users\bigtan\Downloads\CommandTrayHost-0.7-b53\CommandTrayHost\CommandTrayHost.rc	1

**Comment by rexdf** [comment]
仔细看编译说明。其实用Notepad++改一下编码就好了。简而言之，Visual Studio的rc文件不支持UTF-8，而git主要是utf-8格式。 可以参考[这里](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/3082310-support-rc-files-in-utf8-encoding)。
