### ISSUE TITLE
功能请求：增加程序所在目录变量

### ISSUE THREAD

**Issue by bitching** [rexdf/CommandTrayHost#23]
如 CommandTrayHost 和 KCPTun 都放在 E:\program，现在的写法需要写成
"path": "E:\\program\\kcptun.exe"
移动后就失效了，也不能在U盘中执行

期望增加 程序所在目录变量，如 "app"，以上即可写成
"path": "app\\kcptun.exe"

**Comment by rexdf** [comment]
其实现在就支持比如CommandTrayHost.exe所在目录为E:\program\cth\
那么现在指定path和cmd可以参考这个目录，比如kcptun.exe在e:\program\kcptun.exe设置成..\kcptun.exe

也就是相对路劲，只要相对commandtrayhost.exe位置不变就好。

working_directory也是同理

**Comment by bitching** [comment]
Thanks！默认生成的json和Readme里没有提到，还以为不支持。
