### ISSUE TITLE
可以实现分组内子项互斥的功能么？

### ISSUE THREAD

**Issue by bitching** [rexdf/CommandTrayHost#24]
比如我有很多个 config ，做在同一个分组内，启动时运行 item A ，运行的同组的 item B 之前先把 item A 的进程结束掉，即可实现快速切换配置。

**Comment by rexdf** [comment]
有考虑过做组控制（启动，停止之类的）。互斥倒是个好想法，也许加在groups对象里面多一个可选参数exclusion:true这种？但是如果支持嵌套多层，设置不同的exlusion会导致语义复杂化呢. 暂时还没好想好配置方法。

我目前都是全都跑起来就是了。这个实现估计要等到下周，才会有时间，我也顺便考虑下怎么配置比较好。

**Comment by rexdf** [comment]
嗯，我又想到一个新的配置方法了，直接配置在config上面，加一个可选参数exclusion_id:1，相同exclusion_id的只能有一个同时运行，这样实现起来容易。

**Comment by bitching** [comment]
翘首以待。
你的方式更佳，可以不用放在同一分组里面。
要是有参数可以隐藏item的下级菜单（路径、显示、启用、重启菜单），点击即运行就更棒了。
![927](https://user-images.githubusercontent.com/12702029/40570739-77510e00-60c0-11e8-9993-ed81a948279e.png)

**Comment by rexdf** [comment]
暂时简单地加了个互斥id的支持，比较忙，一直拖到今天
