### ISSUE TITLE
only the first command starts when launching the tool

### ISSUE THREAD

**Issue by tangkv** [rexdf/CommandTrayHost#3]
"configs": [
        {
            "name": "gost heroku 1433", // Menu item name in systray
            "path": "C:\\gost", // path which includes cmd exe
            "cmd": "gost -L=:1434 -F=xxx -F=xxxx",
            "working_directory": "", // working directory. empty is same as path
            "addition_env_path": "", //dll search path
            "use_builtin_console": false, //CREATE_NEW_CONSOLE
            "is_gui": false,
            "enabled": true, // run when CommandTrayHost starts
            // Optional
            "require_admin": false, // to run as administrator, problems: User Interface Privilege Isolation
            "start_show": false, // whether to show when start process
            "ignore_all": false, // whether to ignore operation to disable/enable all
        },
        {
            "name": "gost heroku 1434",
            "path": "C:\\gost",
            "cmd": "gost -L=:1434 -F=xxx -F=xxxx",
            "working_directory": "",
            "addition_env_path": "",
            "use_builtin_console": false,
            "is_gui": false,
            "enabled": true,  **-- This flag is set to "true", but this command does not start when launched.**
...
...

**Comment by rexdf** [comment]
瞟一眼readme吧，有中文版本的。 下面有个提示1 提示2 提示3

**Comment by rexdf** [comment]
嗯 还有可能就是被你电脑上其他软件占据了1434端口，导致软件不能打开，gost自己退出了。

**Comment by tangkv** [comment]
确实是因为第二个开始漏掉了 .exe 加上就好了
