### ISSUE TITLE
发现一个bug？

### ISSUE THREAD

**Issue by bitching** [rexdf/CommandTrayHost#30]
可能是feature？
“全部启动”的时候无视了exclusion_id，同一组的都起起来了。
建议同一组的只启动第一项/最后一项，或者看哪一项enabled=true？

**Comment by rexdf** [comment]
之前有人报告过 #27 好像就提到了这个问题。不过那个issue好像因为某种原因消失了。 我看看。

**Comment by rexdf** [comment]
虽然可以用

 `"ignore_all": false, // 是否忽略全部启用禁用操作。当为true时，全部启用菜单对本程序无效` 

来绕过这个问题。但是全部操作好像确实不该启动带有`exclusion_id`的呢。

不过现在问题是，全部启用菜单就永远不会对带有`exclusion_id`的起作用了。
