### ISSUE TITLE
可以加个指定配置文件的选项吗?

### ISSUE THREAD

**Issue by fcying** [rexdf/CommandTrayHost#35]
比如 `CommandTrayHost.exe -c config1.json`, `CommandTrayHost.exe -c config2.json`

方便在不同电脑上使用不同的配置(CommandTrayHost装U盘上)

现在的做法是 复制好几份的 CommandTrayHost 目录使用不同的配置@_@

**Comment by rexdf** [comment]
如果是其他原因不想用config.json这个名字倒好好，也许这个名字会和其他程序的配置名冲突。

多份同时运行有一些其他问题。目前一些内部机制，比如缓存cache文件，以及CommandTrayHost.exe当前所在路径，当前设计上，必须被一份程序独占。所以如果想把同一个CommandTrayHost.exe运行两次，目前是做不到的。和相同的自己是互斥的，和配置文件参数无关。

其实已经尽量控制exe的大小了￣□￣｜｜

**Comment by fcying** [comment]
看来还是挺麻烦的...还是多开几个目录好了....建几个不同名字启动bat放在顶层 也能方便运行...
