### ISSUE TITLE
crontab疑似有bug

### ISSUE THREAD

**Issue by rexdf** [rexdf/CommandTrayHost#39]
放着两个crontab跑了五天，今天回家看到CommanTrayHost自己退出了，原因尚不明，需要更多测试，Windows的CPU开机时间是5天多没重启过。

**Comment by bitching** [comment]
我刚想开个issue来着，我有个程序需要定期跑，启动过后过一段时间就会正常退出，Crontan触发的时候Host就会死掉。。
```
"crontab_config": {
    "crontab": "*/50 * * * * *",
    "method": "start",
    "count": 0,
    "enabled": true,
    "start_show": false,
},
```

不知错误信息有无帮助：
```错误应用程序名称: CommandTrayHost.exe，版本: 1.0.0.0，时间戳: 0x5c1a3c88
错误模块名称: CommandTrayHost.exe，版本: 1.0.0.0，时间戳: 0x5c1a3c88
异常代码: 0xc0000409
错误偏移量: 0x00000000000745fd
错误进程 ID: 0x908
错误应用程序启动时间: 0x01d49df145ab3554
```
![20181227223553](https://user-images.githubusercontent.com/12702029/50483766-2d826280-0a28-11e9-96fb-1ade8076466e.png)

**Comment by Vaire** [comment]
log_leve 选项不能删，删了之后到执行时间就会自动退出

**Comment by bitching** [comment]
> 
> 
> log_leve 选项不能删，删了之后到任务执行时间就会自动退出

噗。。。原来是因为这个，加上```log_level```之后就好了。。。

**Comment by rexdf** [comment]
> log_leve 选项不能删，删了之后到任务执行时间就会自动退出

好吧！知道原因就好解决多了，晚上修复下。
