### ISSUE TITLE
可以设置默认是以隐藏状态启动吗

### ISSUE THREAD

**Issue by SplitGemini** [rexdf/CommandTrayHost#50]
当设置 "enabled": true 时，可以设置默认是隐藏窗口的状态启动吗

**Comment by zt-luo** [comment]
同问，设置了 "start_show": false, // 是否以显示(而不是隐藏)的方式启动子程序 还是会出现窗口

**Comment by zt-luo** [comment]
比较奇怪，可能是我某几个设置出问题，现在  "start_show": false 可以隐藏了
