### ISSUE TITLE
“关于程序重启显示的问题” 默认配置 与 重启配置

### ISSUE THREAD

**Issue by lirener** [rexdf/CommandTrayHost#6]
默认对程序配置
"start_show": false, // 是否以显示(而不是隐藏)的方式启动子程序
如果不想启动程序和开机启动看到窗口 我不对这个设置进行配置（默认不配置不显示）
但是我想重启程序的时候看到窗口为显示 那么我对
cache设置了"disable_cache_show": false, // 禁止缓存显示隐藏状态（这样就是记录）

要怎么做？才能启动程序隐藏所有窗口 --重启单个程序显示窗口呢？

**Comment by rexdf** [comment]
`"start_show": false`这个是单独控制每个程序的，如果没有启用缓存，那么就只受这个控制。

启用缓存，但是`"disable_cache_show": true`，字面意思也就是 禁止缓存显影状态 true就是要禁止，false就是不要禁止。

似乎你被enable和disable开头的命令搞昏了！也许确实不大好理解。这个后面的true与false都是都enable/ disable这件事作用的。

启用缓存，但是`"disable_cache_show": false`  字面意思就是禁止缓存显影状态 不要禁止。 那么这是你可以当做`"start_show": false`这句怎么设置都无效了。虽然第一次是按照这个来的。

然后就是记录的问题，既然你一直在人工读取cache文件。我就说一下cache的意义，每个cache实际上会有一个valid值，这个值被按位使用了。我简单说一下意思。

valid:1 cacha记录的 left，top是有效的，对应于disable_cache_position
valid:2 cache记录的 right bottom是有效的，对应于disable_cache_size
valid:4 cache记录的 enable是有效的，对应于disable_cache_enabled
cache:8 cache记录的 start_show是有效的，对应于disable_cache_show

然后上面的四个的任意组合
valid:3 cache记录的值 left top right bottom是有效的。

**Comment by lirener** [comment]
其实我想 初始化的时候 就是开机启动的时候 窗口都是隐藏的
然后我想打开所有窗口显示的状态下 重启1个窗口他也是显示的 
但是现在好像重启一个是隐藏的

**Comment by rexdf** [comment]
现在重启是显示的么？

**Comment by rexdf** [comment]
是不是已经显示了？

**Comment by lirener** [comment]
现在是 不管我有没有配置"start_show": false, // 是否以显示(而不是隐藏)的方式启动子程序
默认都是隐藏启动的 包括重启也是

然后我配置了cache
"disable_cache_show": false, // 禁止缓存显示隐藏状态
因为这样配置了是重启整个进程才生效 但是我重启过了 似乎再去重启1个窗口也是默认隐藏不显示

**Comment by rexdf** [comment]
这样的配置时缓存当前状态，也就是，你要唤出来再重启，才会期望当前也是显示。不过得看看，这个逻辑我好像忘了加了，只记录在缓存中，主配置的显示状态没有更新

**Comment by lirener** [comment]
是的我是显示出了所有窗口 然后点的重启 但是好像不会跟随当前状态重启

**Comment by lirener** [comment]
对 好像就是缺少当前状态判断的重启！

**Comment by rexdf** [comment]
现在记录功能修复很大，应该各种状态切换和程序退出时都会正常记录了，应该会正常工作了。198版本应该是按预期工作的了。

不仅仅重启样式有了。
