### ISSUE TITLE
 cache会记录不存在的程序为0,0,0,0

### ISSUE THREAD

**Issue by lirener** [rexdf/CommandTrayHost#7]
刚刚发现了一个BUG……就是程序不存在的时候 显隐 cache他会记录不存在的程序为0,0,0,0
![454545](https://user-images.githubusercontent.com/19354130/34056142-d7aba392-e20c-11e7-937b-4c7fbf0d2cae.png)
这样下次再打开的时候加载了这个配置 程序窗口为不可见了……
ddns更新完我就关掉了 然后他也在我的左击[显示隐藏]分组里……不存在了仍然被记录下来

似乎缺少一个窗口关闭了不在对那个窗口进行记录

**Comment by lirener** [comment]
我补充说明一下这个问题
正常情况下一键呼出隐藏的有4个窗口 其中1个为更新ddns的
然后更新完以后 我关闭了那个窗口 继续左击显示隐藏 cache就会记录那个不存在的窗口为0,0,0,0
这个bug就是窗口已经不在了没有启动了 他还能记录的问题

**Comment by rexdf** [comment]
这个逻辑我会修复下，确实是个bug。以前我更新运行状态是在显示菜单的时候。现在得在记录前看一下程序是否还在

**Comment by rexdf** [comment]
换到这个里面来吧，现在这个版本应该修复了很多问题。再试试吧

**Comment by rexdf** [comment]
也就是现在不论怎样都会记录么？

**Comment by rexdf** [comment]
继续找213的bug吧
![500fd9f9d72a60593133ed1e2b34349b033bba96](https://user-images.githubusercontent.com/4038241/34072437-77036ae6-e2c2-11e7-8ff8-7ed9d2d0a7d5.gif)

**Comment by rexdf** [comment]
另外各个窗口分别设置图标也是可以的。我这里每个窗口左上角的图标都不一样

**Comment by lirener** [comment]
额啊
现在超好用的 可以自定义热键启动cmd还能 切换管理员启动 
以前telnet端口会卡住要重启现在启动非常方便……
![360 37](https://user-images.githubusercontent.com/19354130/34072729-89cb9ed2-e2c7-11e7-9674-3347ad337d53.jpg)

**Comment by rexdf** [comment]
啥你在云主机运行啊？

**Comment by lirener** [comment]
不啊 windows10运行

**Comment by rexdf** [comment]
telnet端口是在干啥嘛？我还以为是啥远程连接

 如果是运行命令行 不需要托管的`"not_host_by_commandtrayhost": false, `加这个了可以不停启动无限个

**Comment by lirener** [comment]
telnet啊就是测试一下端口有没开放这样……现在家里的端口经常被关闭 被连接太多搞boom了
"not_host_by_commandtrayhost"原来这个是多开呀 我试试……

**Comment by lirener** [comment]
"not_host_by_commandtrayhost"好像改成true就无法用CommandTrayHost正常启动了
![default](https://user-images.githubusercontent.com/19354130/34072815-0875547a-e2c9-11e7-8d11-9855a7d1a34b.jpg)

**Comment by rexdf** [comment]
可以运行的啊 只是不能监控它了

**Comment by lirener** [comment]
管理员运行可以 正常运行好像跑不起来 那啥 监控是啥？

**Comment by rexdf** [comment]
就是不随着CommandTrayHost退出而退出，也不会记录和更改状态了。好像确实不能 我记得加上去测试的时候还是好的。

**Comment by lirener** [comment]
哦 没事 暂时先这样 既然独立运行了那就不管他了
我还以为可以在托管的情况下重复多开呢

**Comment by rexdf** [comment]
哦 好像是因为受start_show影响

**Comment by rexdf** [comment]
启动了 你在后台看不到它

**Comment by rexdf** [comment]
把start_show这一行注释掉

**Comment by rexdf** [comment]
刚刚你后台应该偷跑了好多个程序

**Comment by lirener** [comment]
晕 还真有

**Comment by rexdf** [comment]
托管多开理论上可以做到，不过似乎会很麻烦，cache位置之类的就不止一个了。先不管托管多开了

**Comment by rexdf** [comment]
本来我打算想管理员一样始终显示的。但是后来一想 万一用户就是想要隐藏呢 所以受start_show影响了 但是没有这行的话 默认是显示的

**Comment by lirener** [comment]
会用了 好的就这样 
![default](https://user-images.githubusercontent.com/19354130/34073028-fa8ae23c-e2cb-11e7-85bc-5f933a5b314f.jpg)
暂时没啥要改的了

**Comment by rexdf** [comment]
好了加了个一起退出的not_monitor_by_commandtrayhost

**Comment by lirener** [comment]
可以 刚刚才发现长按多次好东西要true开启 这样透明度就可以联动调节了

**Comment by rexdf** [comment]
现在调节幅度可自定义了

**Comment by lirener** [comment]
![default](https://user-images.githubusercontent.com/19354130/34076158-c532d9d6-e317-11e7-9c16-ab5ecc788c24.jpg)

**Comment by rexdf** [comment]
![original_masg_554d000137a91e83](https://user-images.githubusercontent.com/4038241/34081440-aa67d1cc-e387-11e7-8cbf-c178e104e229.jpg)

我突然发现似乎可以支持配置热加载，要是变量初始化正常的话，似乎直接就可以。要不要试试

**Comment by lirener** [comment]
好的

**Comment by rexdf** [comment]
https://ci.appveyor.com/project/rexdf/commandtrayhost/build/1.8-b230/artifacts

可以试下这个

**Comment by lirener** [comment]
新版本1.8-b235好像有BUG 那个缓存点是后清空 初始化显示不出来cmd……也就第一次有问题 重启后正常
![1111](https://user-images.githubusercontent.com/19354130/34140296-b657088a-e4b4-11e7-97d4-4e374230784f.png)

**Comment by rexdf** [comment]
哦 好像加载完了之后，确实忘记调用start_all了，现在的效果没启动任何才对？

现在热加载图标，热加载configs都是可以的。

**Comment by lirener** [comment]
![default](https://user-images.githubusercontent.com/19354130/34142115-584810ca-e4c0-11e7-89a2-7cad784e9cbc.jpg)
什么是热加载呀？

**Comment by rexdf** [comment]
我大概用的意思就是不重启程序加载配置

**Comment by lirener** [comment]
soga之前的版本的确不支持这个

**Comment by rexdf** [comment]
你可以试下这个 https://ci.appveyor.com/project/rexdf/commandtrayhost/build/1.8-b241/artifacts

只加了一行代码。
