### ISSUE TITLE
计划任务构想

### ISSUE THREAD

**Issue by rexdf** [rexdf/CommandTrayHost#9]
- [x] 时间是早上7点到8点，运行某个程序A。
- [x] 运行某个程序B如果异常退出了，则自动重启，有一个最大失败次数。
- [x] 每隔30分钟重启一次某个程序C。
- [x] crontab语法格式的计划任务
- [x] 日志

**Comment by rexdf** [comment]
```javscript
{
...
    "crontabs":[
        {
            "crontab": "23 0-20/2 * * *", // crontab语法的时间
            "task": 4, // configs数组下标
            "method": "restart", // restart start stop
            //可选参数
            "count": 2, //最多运行几次, 0为无限多次
            "failed_checker": "", //失败判定,如果用程序返回码GetExitCodeProcess似乎可以很容易做到
            "fail_count": 10, //失败次数
        },
    ],
    "crontab_interval": 300, // 300s检查一次
    "crontab_log": "commandtrayhost_crontab.log",
}
```

**Comment by lirener** [comment]
我这里现在有一个程序有BUG 老会自动退出……比较需要退出自动启动的(2)
因为有开机自动运行了……我也觉得定时自动重启(3)
我选 2、3、5
(5)用于收集BUG有用

**Comment by rexdf** [comment]
现在应该可以用了，只是我自己都没测过。只是写完能编译通过就发布了。

**Comment by rexdf** [comment]
现在比较纠结两个库 https://github.com/staticlibs/ccronexpr ，这个看上去容错性高一些，是比较高质量的库。

https://github.com/Bosma/Scheduler  虽然写的现代C++，而且不仅仅支持crontab，还支持at。然而我对多线程很怀疑。我还是想用Windows内置的Timer来做。

但是Windows内置的Timer有一个问题，最多好像只能支持24天，也就是如果电脑24天不关机或者重启，那么对于要超过24天才开始运行的计划任务就会出问题。这个问题虽然有办法解决，但是暂时比较忙，一时半会不改了。

**Comment by lirener** [comment]
用那个容错率高的ccronexpr
windows10特别不好 我开机24小时 用迅雷和SSR都会卡 高跑CPU
我差不多1~2天就要重启电脑

**Comment by rexdf** [comment]
现在刚刚可以跑了 测试成功

**Comment by rexdf** [comment]
我还加几个边界条件检测 强化一下稳定性 再发一个版本就睡觉

**Comment by lirener** [comment]
![default](https://user-images.githubusercontent.com/19354130/34216344-f41c7482-e5e2-11e7-9499-d2cce4d97f62.jpg)

**Comment by rexdf** [comment]
其实现在你可以用它定时重启电脑 `shutdown /r /t 0`
* 1 2 * * * 每天2点1分运行

如果是要监控一个程序的运行用method的start与restart的区别在于，一个先检测是否在运行再启动，一个会先杀掉再启动。

**Comment by rexdf** [comment]
另外运行时依然受一切其他选项影响，比如size position start_show等

**Comment by lirener** [comment]
// 可选 计划任务
            "crontab_config": { // crontab配置
                "crontab": "0 */1 * * * *", // crontab语法具体参考上面8
                "method": "restart", // 支持的状态有 start restart stop
                "count": 0, // 0 表示infinite不只限制，大于0的整数，表示运行多少次就不运行了
                // 可选
                "enabled": true,
            },
我这样配置 好像他只会重启一次就不会在重启了 配置对了吗？

**Comment by rexdf** [comment]
这个我看上去是每分钟重启一次的意思

**Comment by lirener** [comment]
是啊 但是我看他只重启1次就不重启了……还有我发现其他进程的标题多了选择2个字
![6565656](https://user-images.githubusercontent.com/19354130/34301612-3cca2c48-e768-11e7-8879-c41aa4975a83.png)

**Comment by rexdf** [comment]
可以用一个start_show 的cmd测测看，我瞅一下代码

**Comment by rexdf** [comment]
我有打选择2字么？这好像是什么不得了的错误

**Comment by lirener** [comment]
{
            "name": "测试一下",
            "path": "C:\\Windows\\System32",
            "cmd": "cmd.exe",
            "working_directory": "",
            "addition_env_path": "",
            "use_builtin_console": false,
            "is_gui": false,
            "enabled": true,
            "alpha": 165,
            "start_show": true,
            "crontab_config": { // crontab配置
                "crontab": "0 */1 * * * *", // crontab语法具体参考上面8
                "method": "restart", // 支持的状态有 start restart stop
                "count": 0, // 0 表示infinite不只限制，大于0的整数，表示运行多少次就不运行了
                // 可选
                "enabled": true,
								},
        },
这样配置对吗？确实好像只重启了1次 而且重启过的程序会让任务栏所有窗口闪烁 然后随便点1个窗口就出现了选择那2个字……

**Comment by rexdf** [comment]
啊 难道第二次重启立刻发生了？闪烁是关键。 选择2字是操作系统加上去的。任意命令行选择后标题栏都加上

**Comment by rexdf** [comment]
我要周一才有电脑 现在也修不了bug

**Comment by rexdf** [comment]
重启间隔是多久？调长一点，第二次以后时间是对的么？还有你重启几个窗口？

**Comment by lirener** [comment]
换成"crontab": "0 0/1 * * * *",
好像也是重启一次后不鸟我了

**Comment by lirener** [comment]
1分钟重启1个窗口 重启1次后不会在重启了 没有第2次……
现在调试模式还是1分钟1个窗口 分别2个窗口进行测试

**Comment by rexdf** [comment]
*是对的 我写0是因为*/在那里会表示注释结束

**Comment by lirener** [comment]
如果要无限重启 是不是要把"count": 0, 的0改成很大呀？

**Comment by lirener** [comment]
好像改大了 还是只重启1次

**Comment by rexdf** [comment]
总算找了个不错的客户端，我自己确实只测试能跑一次起来的情况就发布了。
按照我的预期count的0表示无限次，其他就是次数上限。

**Comment by rexdf** [comment]
总算找了个不错的客户端，我自己确实只测试能跑一次起来的情况就发布了。
按照我的预期count的0表示无限次，其他就是次数上限。

**Comment by lirener** [comment]
![default](https://user-images.githubusercontent.com/19354130/34303055-ac8e3ac8-e76e-11e7-9064-02ae21f04706.jpg)

我也是这样觉得 但是实际好像只会重启1次 count我设置999也是1次 然后不管程序开着关闭还是不会在跑了……早点睡 天冷了……

**Comment by rexdf** [comment]
嗯 周一再看了

**Comment by rexdf** [comment]
我发现问题了，你会pull request么？

**Comment by rexdf** [comment]
我发现问题了，你会pull request么？

**Comment by rexdf** [comment]
你把configure.cpp里面1933行的那行代码，到1878那里也套一个

**Comment by rexdf** [comment]
然后队release分支发一个pull request，我merge一下就好了

**Comment by rexdf** [comment]
github网页编辑器真难用，试下最新版。有没有问题也是周一再说

**Comment by lirener** [comment]
可以啦~但是好像重启的窗口不会受到start_show和cache的影响 隐藏/显示

**Comment by lirener** [comment]
哈哈还发现个批量备注的小毛病 那个语法*/会和批量备注冲突 那个斜干能反过来吗？用【\】？
![233](https://user-images.githubusercontent.com/19354130/34332588-65ecb918-e96d-11e7-8423-28a33025a22b.png)

**Comment by rexdf** [comment]
我也不知道会不会自动转义，也许你可以试试json的十六进制表示法来表示*或者/

**Comment by rexdf** [comment]
据我观察室受start_show影响的，不受cache影响是这样设计的。在执行crontab的时候，会全局关掉一切cache，主要是我觉得crontab的自动操作就不要cache了，人工的操作依然会被cache。

**Comment by lirener** [comment]
16进制...要咋弄？那个不是数字才有的东西吗……没听说过16进制的 *或者/

**Comment by rexdf** [comment]
我先考虑一下。
本来我是想说先试下`*\/`这个代替`*/` ，但是我觉得好像还是会有问题。
然后十六进制是json的uncidoe表示法，`"15\u00f8C"`比如这个表示 `"15°C"`

**Comment by rexdf** [comment]
`*\/`代替`*/`这是json规定的，应该可以。不论是否注释应该都是正常的。
```
\"
\\
\/
\b
\f
\n
\r
\t
\u four-hex-digits```

**Comment by lirener** [comment]
哦哦

**Comment by rexdf** [comment]
今天来加个日志？

**Comment by lirener** [comment]
日志 这咋弄 是可以记录程序退出还是打印啥吗
玩玩

**Comment by rexdf** [comment]
某时某分某个crontab被触发了一次，不然比如start这种，都不知道是否运行过

**Comment by lirener** [comment]
OK 这个好

**Comment by lirener** [comment]
啊诺……那个 确实 计划任务crontab 好像有问题 重启无法隐藏……
配置如下：
```
…………
        {
            "name": "ddns ๑乛◡乛๑",
            "path": "C:\\Windows\\System32",
            "cmd": "cmd.exe /c ddns",
            "working_directory": "",
            "addition_env_path": "",
            "use_builtin_console": false,
            "is_gui": false,
            "enabled": true,
            "start_show": false,
            "alpha": 165,
            "hotkey": { // 下面并不需要都出现，可以只设置部分
                "restart": "Alt+D+S", // 重启程序
            			},
            // 可选 计划任务
            "crontab_config": { // crontab配置
                "crontab": "0 */1 * * * *", // crontab语法具体参考上面8
                "method": "restart", // 支持的状态有 start restart stop
                "count": 0, // 0 表示infinite不只限制，大于0的整数，表示运行多少次就不运行了
                // 可选
                "enabled": true,
								},
        },
…………
    "enable_groups": true, // 启用分组菜单
    "groups_menu_symbol": "♂", // 分组菜单标志
    "left_click": [0,1,2,3], // 左键单击显示/隐藏程序 configs序号，从0开始.空数组或者注释掉，则显示CommandTrayHost本体
    "enable_cache": true, // 启用cache
    "conform_cache_expire": true, // 是否弹窗让用户确认是否清空缓存
    "disable_cache_position": false, // 禁止缓存窗口位置
    "disable_cache_size": false, // 禁止缓存窗口大小
    "disable_cache_enabled": true, // 禁止缓存启用禁用状态
    "disable_cache_show": false, // 禁止缓存显示隐藏状态
    "disable_cache_alpha": false, // 禁止缓存透明度 (缓存时只对有alpha值的configs有作用)
…………

```

"start_show": false, //是隐藏启动对不？
"enabled": true, //是主程序启动 伴随着一起执行启动 对不？

**Comment by rexdf** [comment]
还在线么？你测试下鼠标点击ddns的重启会显示出来么？

**Comment by lirener** [comment]
今天基本都在的~右击的好像没问题 显示重启显示 隐藏重启隐藏

**Comment by rexdf** [comment]
这就奇怪了 我来看看怎么回事  实际上crontab的触发动作就是模拟鼠标点击右键的那个菜单。只是我临时禁掉了cache。

**Comment by lirener** [comment]
他好像不会伴随cache和start_show的逻辑 做显/隐
之前修复的重启显示 是使用cache来做依据 重启显/隐 对不
crontab有时候会失效 有时候又有效 也不懂……
-------
顺便问一下那个热加载 是现在配置一改就会不用重启 主程序 就生效了吗？
我刚刚测试改计划任务的时间 好像1分钟改成22分钟 他还是1分钟就重启了

**Comment by rexdf** [comment]
嗯 crontab的热加载暂时还没做，是计划支持的功能，而且好像也比较好做。

**Comment by lirener** [comment]
soga

**Comment by rexdf** [comment]
没有啊 一直是这个 我还是先加日志，有日志才好搞

**Comment by lirener** [comment]
好的

**Comment by rexdf** [comment]
对了你可以测试一下对于单独的cmd 带start_show false也是如此么？至少我这里不是这样

**Comment by lirener** [comment]
我也很奇怪 有时候会出现 现在我改回了22分钟好像也没发现问题 
不过 好的 我再试试~

**Comment by rexdf** [comment]
日志基本上好了，等一分钟应该就会有自动编译的版本出来了

话说你的配置里面的这玩意的效果是啥`"restart": "Alt+D+S",`

**Comment by lirener** [comment]
![livelove](https://user-images.githubusercontent.com/19354130/34336845-95823464-e995-11e7-96c9-c0e999ae6587.jpg)
诶嘿嘿~ 这个是我重启DDNS的热键 按"Alt+D+S"就重启DDNS 没有配置其他 开关 显隐 的了

**Comment by lirener** [comment]
如果我2个窗口用同一个日志文件名 这样会冲突不？

**Comment by rexdf** [comment]
可是<kbd>Alt</kbd>+<kbd>D</kbd>+<kbd>S</kbd>按照我的想法实际上等于<kbd>Alt</kbd>+<kbd>S</kbd>啊

**Comment by rexdf** [comment]
如果不是一起发生 比如秒钟错开 就没事

**Comment by rexdf** [comment]
等会 一定会没事 系统是串联的 一次只能处理一个crontab，没有多线程。所以永远不会发生问题。

**Comment by rexdf** [comment]
最新版的日志格式优化 现在美观多了

**Comment by lirener** [comment]
![360 54](https://user-images.githubusercontent.com/19354130/34338328-7dd50ff0-e9a2-11e7-827c-e2dff2985faa.jpg)

OK更新了 挂机等他出现BUG……

**Comment by rexdf** [comment]
其实我刚刚发现crontab应该是已经支持热加载的了。之前的问题会不会是你的<kbd>Alt</kbd>+<kbd>S</kbd>

**Comment by lirener** [comment]
哈~那我再看看
是不是他提示 是和否 的时候 要点是才会重新呀？我都是点否……

**Comment by rexdf** [comment]
嗯 这倒是个问题，之所以点是重新加载时会删除缓存。考虑的是一种极端情况，如果configs内容换了，或者个数换了。所以干脆删缓存方便。

如果要保留缓存重启点否倒是不错。

**Comment by rexdf** [comment]
也许可以改成三个按钮的对话框，一个重新加载 但是不删缓存

**Comment by lirener** [comment]
如果用现在的否 不重新加载 那样的话 配置就不生效啦？比如那个时间啊或者备注掉什么
我以为这个加载是只有cache的设置的

**Comment by lirener** [comment]
现在的重载配置 主要生效方式就是重启所有窗口的应用……这和手动重启主程序差不多
但是多了个YES[是]删除缓存……对不 难怪我之前不生效了……&

**Comment by rexdf** [comment]
点否就是保留原始配置(内存中有备份)，缓存也是按照原始的更新。

**Comment by lirener** [comment]
是：删除cache + 重启所有[窗口]程序=重新加载
否：保留现有的(下次重启生效conf配置)=就算修改了配置也没生效-因为没重启

对吧

**Comment by rexdf** [comment]
是这样的 现在新加了一个取消按钮 作用是加载配置但是不删缓存

**Comment by rexdf** [comment]
因为内部初始化变量很多嘛，并不很容易恢复到程序刚刚启动时的状态，不然为啥电脑慢了或者啥了 要重启一下呢。热加载的时候要先向系统注销掉一些资源，然后再次申请。

**Comment by rexdf** [comment]
另外弹窗并不是热加载的意思。

热加载仅仅指不重启程序的情况下重新加载配置。广义上也可以指操作系统不重启更新系统核心组件之类的。比如大型网站不关站进行在线升级。

**Comment by lirener** [comment]
![newgame](https://user-images.githubusercontent.com/19354130/34339266-ee7faada-e9ac-11e7-9f8d-785e1cae99db.jpg)
这个热加载还是有一些问题 我也不知道怎么取舍好 还有加不加新的那个按钮
如果只是主程序不重启的话……其他程序重启了 比如那个bittorrent-tracker重启后所有用户会重新连接
感觉也和重启了主程序没区别了……

**Comment by lirener** [comment]
新的不删除按钮就和右击的那个全部重启 一样的效果 对不

**Comment by rexdf** [comment]
新的按钮是啥？我英文系统是Cancel

**Comment by rexdf** [comment]
全部重启是预期的效果，似乎还想重启都不做呢，虽然可以做到，但是感觉会有很大问题

**Comment by lirener** [comment]
不是 我是不想重启

**Comment by lirener** [comment]
比如部分程序重启后数据清0重制了 那样和手动重启差不多……

**Comment by rexdf** [comment]
重启是我手动做的，如果不重启，会有一系列的问题。比如从一个程序改成另一个程序，监控对象就变了。

**Comment by rexdf** [comment]
其实，挂机的单独用一个啊。一般来说我是开两个。这个的内存消耗又不大

**Comment by rexdf** [comment]
这个也太长了。再开新的。

我考虑了一下，如果要做不重启的热加载，而且保证不出错的，必须要检测改动了什么，那样的代码量要翻一倍。几乎整个程序要重写。不想做这个。

而且现在热加载其实就有少量问题，除了热键暂时不能加载，其实某些特殊条件下cache会引发问题。

**Comment by lirener** [comment]
![default](https://user-images.githubusercontent.com/19354130/34339580-0a11688e-e9b1-11e7-8729-ee84aedaf228.gif)
这个 先缓缓 我想想问题出在哪 有点晕

**Comment by lirener** [comment]
暂时先不用加了 我觉得 因为正常要生效配置就是要重启
不想重启的这个问题 发生在测试的时候
包括那个取消不删除 也会逻辑冲突 主要是主程序存在 右击 全部重启 就可以的话就不需要那个不删除了

**Comment by rexdf** [comment]
你截图我看看 为啥是不删除？我以为是 “是” “否” “取消”

加载配置前重启的和菜单中的重启意义不大一样。其实加载配置的重启是两部分，第一部分是停掉全部在运行的程序，然后加载配置，再按照配置的要求运行(也就是启动)。感觉上是重启了。

**Comment by rexdf** [comment]
然而刚刚洗澡时想到了一个解决办法了，似乎有一个取巧的方法。

**Comment by lirener** [comment]
![default](https://user-images.githubusercontent.com/19354130/34339942-15a8bf76-e9b6-11e7-8062-f48d94bf956d.jpg)
